# Generated by Django 5.2.6 on 2025-09-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('total_frames', models.PositiveIntegerField()),
                ('bad_frames', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
